@baseUrl = http://localhost:3333

# @name create_trip
POST {{baseUrl}}/trips
Content-Type: application/json

{
  "destination": "Floripa",
  "starts_at": "2024-06-01 18:00:00",
  "ends_at": "2024-06-02 18:00:00"
}

###

# @name create_trip_validation_error
POST {{baseUrl}}/trips
Content-Type: application/json

{
  "destination": "Floripa",
  "starts_at": "2024-07-08 18:00:00",
  "ends_at": "2024-06-02 18:00:00"
}

###

# @name create_trip_validation_error
POST {{baseUrl}}/trips
Content-Type: application/json

{
  "destination": "Floripa",
  "starts_at": "2024-07-10 18:00:00",
  "ends_at": "2024-07-09 18:00:00"
}


###

# @name create_trip_validation_error
POST {{baseUrl}}/trips
Content-Type: application/json

{
  "destination": "Floripa",
  "starts_at": "2024-07-10 18:00:00",
  "ends_at": "2024-07-18 18:00:00"
}

###

# @name test_email
POST {{baseUrl}}/trips
Content-Type: application/json

{
  "destination": "Floripa",
  "starts_at": "2024-07-10 18:00:00",
  "ends_at": "2024-07-19 18:00:00",
  "owner_name": "Bruno Ramos Lemos",
  "owner_email": "bruno.lemos@live.com",
  "emails_to_invite": [
    "tecbrunoramos@gmail.com",
    "brunolemos@bb.com.br"
  ]
}

###

# @name create_activity
POST {{baseUrl}}/trips/6cbbcf85-fc84-4ba3-ac9b-e176c25a06e8/activities
Content-Type: application/json

{
  "title": "Festinha na praia",
  "occurs_at": "2024-07-12 21:00:00"
}

###

# @name create_activity_error_date
POST {{baseUrl}}/trips/6cbbcf85-fc84-4ba3-ac9b-e176c25a06e8/activities
Content-Type: application/json

{
  "title": "Festinha na praia",
  "occurs_at": "2024-06-30 21:00:00"
}

###

# @name get_activities
GET {{baseUrl}}/trips/6cbbcf85-fc84-4ba3-ac9b-e176c25a06e8/activities

###

# @name create_link
POST {{baseUrl}}/trips/6cbbcf85-fc84-4ba3-ac9b-e176c25a06e8/links
Content-Type: application/json

{
  "title": "Reserva AIRBNB",
  "url": "http://airbnb.com.br/orderid"
}

###

# @name get_links
GET {{baseUrl}}/trips/6cbbcf85-fc84-4ba3-ac9b-e176c25a06e8/links

###

# @name get_participant
GET {{baseUrl}}/participants/d3c22a80-760a-46b5-a335-0c5a35ebc7ac

###

# @name get_links
GET {{baseUrl}}/trips/6cbbcf85-fc84-4ba3-ac9b-e176c25a06e8/participants